name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  style_check:
    runs-on: ubuntu-latest
    name: style-check
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: yarn --dev
      - name: Run eslint check
        run: yarn lint
      - name: Run prettier check
        run: yarn format-ci
